name: mtg-friends
root: ~/src/personal-projects/mtg-friends

windows:
  - shell:
      layout: even-horizontal
      panes:
        - code ~/src/elixir-phoenix.code-workspace
        - mix phx.server
