name: mtg-friends
root: ~/src/personal-projects/mtg-friends

windows:
  - shell:
      layout: even-vertical
      panes:
        - code ~/src/elixir-phoenix.code-workspace
        - psql -h localhost -p 5432 -d "mtg_friends_dev"
  - server: mix phx.server
