# fly.toml app configuration file generated for mtg-friends on 2025-08-22T08:32:24+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mtg-friends'
primary_region = 'mia'
kill_signal = 'SIGTERM'

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'gettiebreaker.com'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000
